import React, { useState } from "react"
import "./styles.scss"

const tools = [
  ["Lead Metrics", "Compare lead volumes and trends by period, branch, source, or domain."],
  ["Conversion Report", "Understand funnel movement and conversion performance."],
  ["Stale Lead Detection", "Find leads with no recent activity for timely review."],
  ["Lead List", "Drill into filtered, permission-aware lead records."],
  ["Lead Details", "View a permitted single-lead summary and history."],
  ["Task Visibility", "Review existing tasks and follow-up workload."],
  ["Marketing Target Progress", "Compare primary, easy-to-sell, and high-value targets with achievement."],
]

const Card = ({ children, className = "" }) => <div className={`copilot-card ${className}`}>{children}</div>

export default function CopilotArchitecture() {
  const [tab, setTab] = useState("architecture")
  return <div className="copilot-page">
    <header className="copilot-hero"><div className="copilot-mark">▥</div><h1>SRV Tech Team · CRM Copilot</h1><p>AI-Powered Analytical Assistant for Live CRM Data</p><small>Solution Architecture & Implementation Plan · Prepared by Smotpro</small></header>
    <main>
      <section><h2>📊 Current Challenges</h2><div className="copilot-stats"><Card><b>Live CRM</b><span>Single source of truth</span></Card><Card><b>Read-only</b><span>Analytical access</span></Card><Card><b>7</b><span>Planned analytical tools</span></Card><Card><b>21 days</b><span>Proposed delivery schedule</span></Card></div><Card className="challenge-box"><h3>Key Challenges</h3><p>Teams currently spend time filtering records, exporting reports, preparing summaries, and repeating the same work for every follow-up question. The Copilot brings live analysis into the CRM conversation.</p></Card></section>
      <section className="light-section"><h2>🗂️ Data Landscape</h2><div className="green-panel"><h3>Processing Requirements</h3><div className="copilot-grid"><Card><b>Lead Data</b><p>Current lead volume, source, branch, domain, and ownership analysis.</p></Card><Card><b>Activity Data</b><p>Follow-up history and stale-lead identification.</p></Card><Card><b>Target Data</b><p>Marketing target achievement by configured period and category.</p></Card><Card><b>Access Context</b><p>User identity, branch, domain, and privilege scope.</p></Card></div></div></section>
      <section><h2>🏗️ System Architecture</h2><div className="tabs"><button className={tab === "architecture" ? "active" : ""} onClick={() => setTab("architecture")}>🏗️ Architecture</button><button className={tab === "flow" ? "active" : ""} onClick={() => setTab("flow")}>🔄 Query Flow</button><button className={tab === "scope" ? "active" : ""} onClick={() => setTab("scope")}>📋 Scope</button></div><Card className="diagram">{tab === "architecture" && <><div className="layer blue">CRM Interface<small>Copilot chat panel</small></div><i>↓ User question</i><div className="layer orange">Authenticated CRM Gateway<small>Session and access context</small></div><i>↓ Governed request</i><div className="layer green">AI Orchestration &amp; Tool Layer<small>Routing · validation · response preparation</small></div><i>↓ Live retrieval</i><div className="layer pink">Existing CRM Services<small>Reports · leads · follow-ups · marketing targets</small></div></>}{tab === "flow" && <div className="flow-list">{["User asks a question", "Question is understood and structured", "User permissions are applied", "Approved CRM data is retrieved", "Answer, table, or chart is returned"].map((x, i) => <div key={x}><strong>{i + 1}</strong>{x}</div>)}</div>}{tab === "scope" && <div className="scope-list"><p>✅ Included: read-only analytical queries</p><p>✅ Included: live CRM data and marketing-target progress</p><p>✅ Included: conversational drill-down</p><p>⏳ Future: lead assignment, task creation, stage changes, and other write actions</p></div>}</Card><div className="stack-inline"><h3>💻 Technical Stack</h3><p className="section-note">Planned technologies and their role in delivering the solution.</p><div className="stack-grid">{[["React", "Chat interface and visual reporting"], ["Node.js", "CRM integration and authenticated access"], ["MongoDB", "Existing CRM data source"], ["Python · FastAPI", "AI service and request handling"], ["LangGraph", "Conversation and analytical workflow"], ["MCP", "Controlled analytical capabilities"], ["Gemini", "Question understanding and response generation"], ["Pydantic", "Request and response validation"], ["Redis", "Conversation state and lookup caching"], ["Guardrails", "Response checks and scope protection"]].map(([name, role]) => <div className="stack-item" key={name}><b>{name}</b><span>{role}</span></div>)}</div></div></section>
      <section className="purple-section"><h2>🧰 Functional Capabilities</h2><div className="copilot-grid">{tools.map(([title, text]) => <Card key={title}><b>{title}</b><p>{text}</p></Card>)}</div></section>
      <section><h2>🛡️ Guardrails &amp; Safety</h2><div className="copilot-grid safety">{[["🔐", "Permission Control", "Access scope comes from the authenticated CRM session."],["🚫", "Read-only Boundary", "The assistant provides analytical access without changing CRM records."],["✓", "Reliable Calculations", "Business calculations remain in governed CRM services."],["📝", "Auditability", "Requests, tool calls, outcomes, and responses are traceable."],["⚠️", "Scope Control", "Unsupported questions receive a clear limitation response."],["👤", "Privacy", "Only permitted CRM information is presented to the user."]].map(([icon, title, text]) => <Card key={title}><em>{icon}</em><b>{title}</b><p>{text}</p></Card>)}</div></section>
      <section className="light-section"><h2>⚡ Performance &amp; Scalability</h2><div className="performance"><Card><h3>Design Requirements</h3><p>Live API querying, structured responses, progress indicators, measured tool performance, and scalable orchestration.</p></Card><div className="copilot-stats"><Card><b>&lt; 3s</b><span>Target response experience</span></Card><Card><b>p95</b><span>Measured before SLA commitment</span></Card></div></div></section>
      <section><h2>🗓️ Implementation Roadmap · 21 Days</h2><p className="section-note">Proposed schedule from kickoff, with CRM access and business requirements available at the start.</p><div className="roadmap">{[["Days 1–3", "Discovery & design", "Agree on business questions, access rules, data definitions, and presentation design."],["Days 4–10", "CRM connection & analytics", "Connect live CRM services and prepare the seven analytical capabilities with permission controls."],["Days 11–16", "Conversation & experience", "Build the chat experience, tables, charts, follow-up questions, safeguards, and activity tracking."],["Days 17–21", "Validation & handover", "Validate real questions with business users, measure performance, resolve issues, and prepare release and handover." ]].map(([days, title, text]) => <Card key={days}><strong>{days}</strong><h3>{title}</h3><p>{text}</p></Card>)}</div></section>
    </main><footer>SRV Tech Team · CRM Copilot · Confidential</footer>
  </div>
}
